name: Deploy to Vercel (Production)

on:
  push:
    branches:
      - main  # only deploy when main is updated

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Vercel Deploy
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/https://api.vercel.com/v1/integrations/deploy/prj_xvn1VZ7WZe2jQ5DjuYBQoiFiPyj1/UQxhMwLkoo
