name: Frontend Tests

on:
  push:
    branches: [ main, update/testingS3 ]
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci
      
      - name: Run tests with coverage
        run: npm run test:ci
        
      # Upload to Codecov - use lcov.info instead of clover.xml
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./frontend/coverage
          flags: frontend
          name: frontend-coverage

      - name: Upload coverage to GitHub (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage